services:
  backend:
    container_name: compose-kpd-back-container
    build:
      context: backend
      dockerfile: Dockerfile
    image: kpd-back-optimal-image
    networks:
      - backend
    ports:
      - 4000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    container_name: compose-kpd-front-container
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kpd-front-optimal-image
    networks:
      - frontend
    ports:
      - 3005:80
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - backend
    ports:
      - 8081:8080
    depends_on:
      - postgres
    restart: always

networks:
  frontend:
  backend:

volumes:
  postgres_data:
